### ISSUE TITLE
ERB processing only applies to FigNewton.load('filename')

### ISSUE THREAD

**Issue by tk8817** [cheezy/fig_newton#12]
Hey @cheezy , I noticed today that loading via ENV does not support ERB. When you use FigNewton.load, the YAML is handled by your yml_reader gem which does ERB interpolation. When you use  ENV['FIG_NEWTON_FILE'], FigNewton loads the yaml within itself and that method has no ERB interpolation. 

I would suggest that FigNewton always call the yml_reader .load method to ensure parity regardless of entry point. yml_reader is included as a dependancy on FigNewton so this should be a quick win.

``` ruby
# ERB processed
FigNewton.load('data.yml')  
```

``` ruby
# Non ERB processed
ENV['FIG_NEWTON_FILE']='data.yml'
```

**Comment by cheezy** [comment]
Done my friend! :)
